In [96]:
import numpy as np
import pandas as pd

df = pd.read_json("./data.json")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   className        101 non-null    object
 1   classId          101 non-null    int64
 2   coarseClassName  101 non-null    object
 3   imagePath        101 non-null    object
 4   productType      101 non-null    object
 5   description      71 non-null     object
 6   country          97 non-null     object
 7   volume           101 non-null    object
 8   key              101 non-null    object
dtypes: int64(1), object(8)
memory usage: 7.2+ KB

In [85]:
vg = pd.DataFrame(
    [
        {"id": "59", "price": 1.5, "stockLevel": 250},
        {"id": "60", "price": 0.5, "stockLevel": 250},
        {"id": "61", "price": 1, "stockLevel": 250},
        {"id": "63", "price": 0.3, "stockLevel": 250},
        {"id": "64", "price": 0.05, "stockLevel": 250},
        {"id": "65", "price": 0.1, "stockLevel": 250},
        {"id": "66", "price": 0.6, "stockLevel": 250},
        {"id": "67", "price": 0.2, "stockLevel": 250},
        {"id": "68", "price": 0.3, "stockLevel": 250},
        {"id": "69", "price": 0.2, "stockLevel": 250},
        {"id": "70", "price": 0.2, "stockLevel": 250},
        {"id": "71", "price": 0.2, "stockLevel": 250},
        {"id": "73", "price": 1, "stockLevel": 250},
        {"id": "75", "price": 0.7, "stockLevel": 250},
        {"id": "76", "price": 0.5, "stockLevel": 250},
        {"id": "77", "price": 0.3, "stockLevel": 250},
        {"id": "78", "price": 0.2, "stockLevel": 250},
        {"id": "79", "price": 0.15, "stockLevel": 250},
        {"id": "80", "price": 0.9, "stockLevel": 250},
        {"id": "72", "price": 0.2, "stockLevel": 250},
        {"id": "74", "price": 1, "stockLevel": 250},
        {"id": "62", "price": 0.2, "stockLevel": 250},
    ]
)

In [86]:
fj = pd.DataFrame(
    [
        {"id": "0", "price": 1.2, "stockLevel": 27},
        {"id": "1", "price": 1, "stockLevel": 15},
        {"id": "2", "price": 1.4, "stockLevel": 20},
        {"id": "3", "price": 1.1, "stockLevel": 23},
        {"id": "4", "price": 1.5, "stockLevel": 30},
        {"id": "5", "price": 2, "stockLevel": 19},
        {"id": "6", "price": 0.5, "stockLevel": 25},
        {"id": "7", "price": 0.9, "stockLevel": 22},
        {"id": "8", "price": 0.7, "stockLevel": 18},
        {"id": "9", "price": 0.8, "stockLevel": 20},
        {"id": "10", "price": 2.5, "stockLevel": 27},
        {"id": "11", "price": 3, "stockLevel": 15},
        {"id": "12", "price": 3, "stockLevel": 16},
        {"id": "13", "price": 2.8, "stockLevel": 17},
        {"id": "14", "price": 3.5, "stockLevel": 29},
        {"id": "15", "price": 1.4, "stockLevel": 24},
        {"id": "16", "price": 0.9, "stockLevel": 28},
        {"id": "17", "price": 2.7, "stockLevel": 20},
        {"id": "18", "price": 2, "stockLevel": 15},
        {"id": "19", "price": 1.3, "stockLevel": 22},
        {"id": "20", "price": 0.8, "stockLevel": 12},
        {"id": "21", "price": 0.9, "stockLevel": 18},
        {"id": "22", "price": 1.1, "stockLevel": 15},
        {"id": "23", "price": 2.5, "stockLevel": 30},
        {"id": "24", "price": 1.2, "stockLevel": 25},
        {"id": "25", "price": 1.6, "stockLevel": 20},
        {"id": "26", "price": 1.8, "stockLevel": 16},
        {"id": "27", "price": 0.7, "stockLevel": 22},
    ]
)

In [87]:
mp = pd.DataFrame(
    [
        {"id": "86", "price": 25, "stockLevel": 65},
        {"id": "90", "price": 30, "stockLevel": 55},
        {"id": "74", "price": 1.2, "stockLevel": 110},
        {"id": "68", "price": 0.8, "stockLevel": 130},
        {"id": "88", "price": 60, "stockLevel": 40},
        {"id": "85", "price": 55, "stockLevel": 25},
        {"id": "81", "price": 35, "stockLevel": 45},
        {"id": "66", "price": 0.7, "stockLevel": 110},
        {"id": "72", "price": 0.4, "stockLevel": 132},
        {"id": "89", "price": 75, "stockLevel": 15},
        {"id": "67", "price": 0.5, "stockLevel": 140},
        {"id": "60", "price": 0.6, "stockLevel": 200},
        {"id": "75", "price": 0.9, "stockLevel": 95},
        {"id": "78", "price": 0.26, "stockLevel": 80},
        {"id": "82", "price": 40, "stockLevel": 50},
        {"id": "59", "price": 3.4, "stockLevel": 100},
        {"id": "87", "price": 48, "stockLevel": 50},
        {"id": "71", "price": 0.4, "stockLevel": 160},
        {"id": "83", "price": 38, "stockLevel": 70},
        {"id": "84", "price": 45, "stockLevel": 30},
    ]
)

In [88]:
df.head()

,className,classId,coarseClassName,imagePath,productType,description,country,volume,key
0,Golden-Delicious,0,Apple,./images/Fruit/Apple/Golden-Delicious/Golden-D...,Fruit,Golden Delicious has a white juicy pulp and a ...,Italy,180g,fruit/apple/golden_delicious
1,Granny-Smith,1,Apple,./images/Fruit/Apple/Granny-Smith/Granny-Smith...,Fruit,"Granny Smith is a green apple with white, firm...",Italy,180g,fruit/apple/granny_smith
2,Pink-Lady,2,Apple,./images/Fruit/Apple/Pink-Lady/Pink-Lady_Iconi...,Fruit,"Pink Lady reminds of Royal Gala, though it is ...",Italy,180g,fruit/apple/pink_lady
3,Red-Delicious,3,Apple,./images/Fruit/Apple/Red-Delicious/Red-Delicio...,Fruit,Red Delicious is a dark red apple with relativ...,Italy,160g,fruit/apple/red_delicious
4,Royal-Gala,4,Apple,./images/Fruit/Apple/Royal-Gala/Royal-Gala_Ico...,Fruit,"Royal Gala is a crispy and very juicy apple, w...",Argentina,180g,fruit/apple/royal_gala

In [89]:
all_vendors = pd.concat([vg, fj, mp])
all_vendors["id"] = all_vendors["id"].astype(int)
all_vendors

    id  price  stockLevel
0   59   1.50         250
1   60   0.50         250
2   61   1.00         250
3   63   0.30         250
4   64   0.05         250
..  ..    ...         ...
15  59   3.40         100
16  87  48.00          50
17  71   0.40         160
18  83  38.00          70
19  84  45.00          30

[70 rows x 3 columns]

In [90]:
all_vendors.groupby("id").agg({"price": "max", "stockLevel": "sum"}).reset_index().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          60 non-null     int64
 1   price       60 non-null     float64
 2   stockLevel  60 non-null     int64
dtypes: float64(1), int64(2)
memory usage: 1.5 KB

In [91]:
df[["classId"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   classId  101 non-null    int64
dtypes: int64(1)
memory usage: 936.0 bytes

In [97]:
combo = all_vendors.groupby("id").agg({"price": "max", "stockLevel": "sum"}).merge(df[["classId", "productType"]], right_on="classId", left_index=True, how="right")

In [98]:
df["productType"].unique()

array(['Fruit', 'Packages', 'Vegetables', 'Reptiles', 'Oddity'],
      dtype=object)

In [99]:
multiplier = {
    "Fruit": 2,
    "Packages": 4,
    "Vegetables": 2,
    "Reptiles": 100,
    "Oddity": 1000,
}

In [105]:
np.random.seed(42) # answer to the ultimate question of life, the universe, and everything
df["price"] = pd.Series(np.random.rand(len(combo)))
df["stockLevel"] = pd.Series(np.random.randint(5, 30, len(combo))) * 10
df["price"] = df["price"] * df["productType"].map(multiplier)
df["price"] = df["price"].round(2)
df

,className,classId,coarseClassName,imagePath,productType,description,country,volume,key,price,stockLevel
0,Golden-Delicious,0,Apple,./images/Fruit/Apple/Golden-Delicious/Golden-D...,Fruit,Golden Delicious has a white juicy pulp and a ...,Italy,180g,fruit/apple/golden_delicious,0.75,110
1,Granny-Smith,1,Apple,./images/Fruit/Apple/Granny-Smith/Granny-Smith...,Fruit,"Granny Smith is a green apple with white, firm...",Italy,180g,fruit/apple/granny_smith,1.90,210
2,Pink-Lady,2,Apple,./images/Fruit/Apple/Pink-Lady/Pink-Lady_Iconi...,Fruit,"Pink Lady reminds of Royal Gala, though it is ...",Italy,180g,fruit/apple/pink_lady,1.46,240
3,Red-Delicious,3,Apple,./images/Fruit/Apple/Red-Delicious/Red-Delicio...,Fruit,Red Delicious is a dark red apple with relativ...,Italy,160g,fruit/apple/red_delicious,1.20,80
4,Royal-Gala,4,Apple,./images/Fruit/Apple/Royal-Gala/Royal-Gala_Ico...,Fruit,"Royal Gala is a crispy and very juicy apple, w...",Argentina,180g,fruit/apple/royal_gala,0.31,90
...,...,...,...,...,...,...,...,...,...,...,...
96,Teleportation Donuts,96,Pastries,food/pastries/teleportation-donuts.jpg,Oddity,These magical donuts are infused with teleport...,Multiverse,6 units,food/pastries/teleportation-donuts,522.73,70
97,Invisible Umbrella,97,Accessories,functional/accessories/invisible-umbrella.jpg,Oddity,Experience the ultimate surrealist accessory w...,Dreamland,1 unit,functional/accessories/invisible-umbrella,427.54,240
98,Levitating Teapot,98,Teaware,functional/teaware/levitating-teapot.jpg,Oddity,Brew your tea in style with this levitating te...,Wonderland,500 ml,functional/teaware/levitating-teapot,25.42,80
99,Singing Pasta,99,Pasta dishes,vegetable/pasta-dishes/singing-pasta.jpg,Oddity,Indulge in this zany dish of singing pasta. As...,Melodia,2 servings,vegetable/pasta-dishes/singing-pasta,107.89,230
100,Time-Traveling Alarm Clock,100,Clocks,functional/clocks/time-traveling-alarm-clock.jpg,Oddity,Wake up to a surreal morning with this time-tr...,Chronopolis,1 unit,functional/clocks/time-traveling-alarm-clock,31.43,70

In [112]:
df["classId"] = df["classId"].astype(str)
df[["classId", "price", "stockLevel"]].to_json("items.json", orient="records")

In [75]:
n_df = pd.DataFrame([
    {
        "class_name": "Gravity-Defying Shoes",
        "classId": "91",
        "coarse_class_name": "Footwear",
        "product_type": "Functional",
        "description": "Walk on air with these gravity-defying shoes. With their anti-gravitational technology, you'll experience the sensation of floating as you stroll through your everyday adventures.",
        "country": "Cloud Nine",
        "volume": "1 pair",
    },
    {
        "class_name": "Talking Plant Pot",
        "classId": "92",
        "coarse_class_name": "Home decor",
        "product_type": "Functional",
        "description": "Bring your plants to life with the talking plant pot. It converses with your plants, providing them with uplifting compliments and motivational speeches, fostering a nurturing environment.",
        "country": "Botanica",
        "volume": "1 unit",
    },
    {
        "class_name": "Glow-in-the-Dark Pancakes",
        "classId": "93",
        "coarse_class_name": "Breakfast",
        "product_type": "Food",
        "description": "Start your day with a whimsical twist by indulging in glow-in-the-dark pancakes. These magical delights emit a soft glow, turning your breakfast into an ethereal experience.",
        "country": "Lumos",
        "volume": "3 pancakes",
    },
    {
        "class_name": "Infinity Mirror Sunglasses",
        "classId": "94",
        "coarse_class_name": "Eyewear",
        "product_type": "Functional",
        "description": "Step into a never-ending world of style with these infinity mirror sunglasses. The reflective surfaces create an infinite tunnel of mesmerizing visuals, making a bold statement wherever you go.",
        "country": "Reflectopia",
        "volume": "1 pair",
    },
    {
        "class_name": "Absurdly Flexible Yoga Mat",
        "classId": "95",
        "coarse_class_name": "Fitness accessories",
        "product_type": "Functional",
        "description": "Push the boundaries of flexibility with this absurdly flexible yoga mat. It stretches, twists, and contorts in unimaginable ways, challenging you to explore new realms of body movement.",
        "country": "Flexiverse",
        "volume": "1 unit",
    },
    {
        "class_name": "Teleportation Donuts",
        "classId": "96",
        "coarse_class_name": "Pastries",
        "product_type": "Food",
        "description": "These magical donuts are infused with teleportation properties. Each bite transports you to a random location around the world, creating a truly unique and unexpected culinary experience.",
        "country": "Multiverse",
        "volume": "6 units",
    },
    {
        "class_name": "Invisible Umbrella",
        "classId": "97",
        "coarse_class_name": "Accessories",
        "product_type": "Functional",
        "description": "Experience the ultimate surrealist accessory with the Invisible Umbrella. Despite its transparent appearance, this umbrella shields you from rain and sun. It's an extraordinary conversation starter.",
        "country": "Dreamland",
        "volume": "1 unit",
    },
    {
        "class_name": "Levitating Teapot",
        "classId": "98",
        "coarse_class_name": "Teaware",
        "product_type": "Functional",
        "description": "Brew your tea in style with this levitating teapot. It defies gravity as it floats mid-air, pouring your favorite tea with a touch of whimsy. A true spectacle for tea lovers.",
        "country": "Wonderland",
        "volume": "500 ml",
    },
    {
        "class_name": "Singing Pasta",
        "classId": "99",
        "coarse_class_name": "Pasta dishes",
        "product_type": "Vegetable",
        "description": "Indulge in this zany dish of singing pasta. As the pasta cooks, it emits melodious tunes and harmonious lyrics. A bizarre culinary experience that delights both the ears and taste buds.",
        "country": "Melodia",
        "volume": "2 servings",
    },
    {
        "class_name": "Time-Traveling Alarm Clock",
        "classId": "100",
        "coarse_class_name": "Clocks",
        "product_type": "Functional",
        "description": "Wake up to a surreal morning with this time-traveling alarm clock. It not only wakes you up but also transports you to a random era in history. Start your day with an adventure.",
        "country": "Chronopolis",
        "volume": "1 unit",
    },
])

n_df["key"] = n_df[["product_type", "coarse_class_name", "class_name"]].apply(lambda x: "/".join(x.values), axis=1).str.lower().str.replace("_", "-").str.replace(" ", "-")
n_df["image_path"] = n_df["key"] + ".jpg"
n_df = n_df.rename(columns={"class_name": "className", "classId": "classId", "coarse_class_name": "coarseClassName", "product_type": "productType", "image_path": "imagePath"})

# n_df.to_dict(orient="records")

In [77]:
n_df[["productType", "coarseClassName"]].value_counts()

productType  coarseClassName
Food         Breakfast              1
             Pastries               1
Functional   Accessories            1
             Clocks                 1
             Eyewear                1
             Fitness accessories    1
             Footwear               1
             Home decor             1
             Teaware                1
Vegetable    Pasta dishes           1
dtype: int64